# azure-pipelines.yml
trigger:
  branches:
    include:
      - main  # or 'master', depending on your default branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m venv antenv
      source antenv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      source antenv/bin/activate
      python -m pytest
    displayName: 'Run tests'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'MARZIHEIDARI_asp_3018'
      appName: 'flask-ml-app'
      package: $(System.DefaultWorkingDirectory)
